sysprog21/semu

scripts/download.sh

- Make download script work on macOS where `curl` is installed by default.
- Thank you for making this emulator :)
- On my Mac (macOS Monterey 12.4):
```Shell
➜  semu git:(master) ✗ make distclean check
rm -f semu
rm -f kernel.bin fs.img
cc -O2 -Wall -o semu semu.c -lpthread
scripts/download.sh
Downloading...
kernel.bin: OK
fs.img: OK
./semu kernel.bin fs.img
xv6 kernel is booting
init: starting sh
$ echo
echo
$ ^Cmake: *** [check] Interrupt: 2
```

Make use of 'curl' in macOS

---

.gitmodules
Makefile
semu.c
tests/isa-test.c
tests/test.h

As the discussion in the issue ticket.
This patch first supports **./semu  --test** command to run all test binaries and show the test result like:
```
$ make test
cc -O2 -Wall -Iinclude -o semu semu.c test/test.c -lpthread
./semu --test
Test binary rv64ui_p_fence_i failed...
An exception occurred.
Test binary rv64ua_p_amoadd_w failed...
Fail test case = 2.
Test binary rv64ua_p_amoand_d failed...
An exception occurred.
Pass: rv64ui_p_add
Pass: rv64ui_p_addi
Pass: rv64ui_p_addiw
Pass: rv64ui_p_addw
Pass: rv64ui_p_and
Pass: rv64ui_p_andi
Pass: rv64ui_p_auipc
Fail: rv64ui_p_fence_i
...
Pass: rv64ui_p_jal
...
Pass: rv64ua_p_amoadd_d
Fail: rv64ua_p_amoadd_w
Fail: rv64ua_p_amoand_d
=======================
Test result: 51/54
=======================
```
A new entry point is declared to execute …

Integrate riscv-tests

---

Makefile

Only build isa tests of riscv-tests for saving build time.
Also, autoconf is unnecessary since there is a pre-generated configure
file in riscv-tests repository. See issue #273:
https://github.com/riscv-software-src/riscv-tests/issues/273

Optimize riscv-tests build flow

---

semu.c

Refer to RISC-V specification: "The RISC-V Instruction Set Manual
Volume I: Unprivileged ISA", Section 8.4:
For RV64, 32-bit AMOs always sign-extend the value placed in rd.
And the recent test result of riscv-tests becomes:
```
Pass: rv64ua_p_amoadd_w
Pass: rv64ua_p_amoswap_w
=======================
Test result: 55/71
=======================
```

Fix RV32A instructions

---

README.md
semu.c
tests/isa-test.c
tests/test.h

Current test command always tests whole test cases. This patch
adds an option to run just one specific test case. It is useful
when we plan to re-run certain instruction test(s). For example:
./semu --test rv64ui_p_add
Also, this patch makes the log of test result more pretty.
Now the test log would be:
[ RUN      ] rv64ua_p_lrsc
a0 = 0x80002008
tohost = 0x53b
An exception occurred.
[  FAILED  ] rv64ua_p_lrsc
[==========] 71 test from riscv-tests ran
[  PASSED  ] 55 test
[  FAILED  ] 16 test, listed below:
[  FAILED  ] rv64ui_p_fence_i
[  FAILED  ] rv64ua_p_amoand_d

Add option to test specific test binary

---

semu.c

Previous code only checks if the register a0 equals zero or not to
determine if the test is passed. But there will be a bug if semu has
not implemented the tested instruction yet. Semu always regards this
kind of instruction as an illegal instruction, and further triggers
an exception. If there is an exception, the riscv-tests will set the
"tohost" variable other than 1, and stuck in an infinite loop. Since
the test is not finished, the value of a0 is meaningless.
This patch fixes the pass condition that semu checks not only a0,
but also the tohost variable, to determine the result of the test.

Fix the pass condition of riscv-tests

---

README.md
tests/isa-test.c

Remove duplicated test item, now the result of riscv-tests should be:
[  FAILED  ] rv64ua-p-lrsc
[==========] 70 test(s) from riscv-tests ran.
[  PASSED  ] 54 test(s).
[  FAILED  ] 16 test(s), listed below:
[  FAILED  ] rv64ui-p-fence_i
[  FAILED  ] rv64ua-p-amoand_d

Remove duplicated test item

---

README.md
scripts/gen-isa-test-list.sh

- Refer to https://github.com/riscv-software-src/riscv-tests/issues/190 in README
- It could be just me, but `scripts/gen-isa-test-list.sh` doesn't iterate through the `testdata` struct in `isa-test.c`. I tested it on bash version `3.2.57(1)-release` (on macOS Monterey 12.4) as well as on `version 4.2.46(2)-release` (on CentOS 7). Here is the result:
```shell
$ ./gen-isa-test-list.sh 
rv64ui-p-add
$ cat /etc/*-release
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
```
- Therefore, I replaced the here string with process substitution in `scripts/gen-isa-test-list.sh`.
- Ran `gen-isa-test-list.sh ` on CentOS 7 and macOS Monterey 12.4:
```shell
$ ls -R 
gen-isa-test-list.sh  tests
./tests:     
isa-test.c 
$ ./gen-isa-test-list.sh 
rv64ui-p-add 
rv64ui-p-addi    
rv64ui-p-addi …
```

Minor improvements for macOS users

---

mk/riscv-tests.mk

- It could be just me, but it seems like the extra parentheses made `cd $(RISCV_TESTS_DIR); ./configure` ineffective. Therefore, the `Makefile` in `tests/riscv-tests` wasn't generated when I built a fresh checkout of `semu`.
- Tested on macOS Monterey 12.4. I'll try to test it on CentOS tomorrow.
- Thanks for making the build modularized :)
- Here is a fresh checkout of the `semu` repo
```shell
➜  semu git:(master) git diff
➜  semu git:(master) git s
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
➜  semu git:(master) make ENABLE_RISCV_TESTS=1 clean run-tests        
CC	semu.o
CC	tests/isa-test.o
(omitted)
Building riscv-tests...
riscv64-unknown-elf-objcopy: 'tests/riscv-tests/isa/rv64ui-p-add': No such file
make: *** …
```

Remove extra parentheses

---

README.md
mul128.h
semu.c
tests/isa-test.c

Implements more RV64M instructions and adds corresponding tests. Now the result of tests becomes:
[ RUN      ] rv64ua-p-lrsc
a0 = 0x80002008
tohost = 0x53b
An exception occurred.
[  FAILED  ] rv64ua-p-lrsc
[==========] 83 test(s) from riscv-tests ran.
[  PASSED  ] 67 test(s).
[  FAILED  ] 16 test(s), listed below:
[  FAILED  ] rv64ui-p-fence_i
[  FAILED  ] rv64ua-p-amoand_d

Implement more RV64M instructions

---

README.md
semu.c

Besides, the static keyword is added to the inline functions to fix undefined reference issue and let the compiler force inline those functions.
Now the result of tests becomes:
[==========] 83 test(s) from riscv-tests ran.
[  PASSED  ] 81 test(s).
[  FAILED  ] 2 test(s), listed below:
[  FAILED  ] rv64ui-p-fence_i
[  FAILED  ] rv64ua-p-lrsc

Implement RV32 and RV64 AMO instructions.

---

semu.c

For AMOs, the A extension requires that the address held in rs1 be naturally aligned to the size of the operand (i.e., eight-byte aligned for 64-bit words and four-byte aligned for 32-bit words). If the address is not naturally aligned, an address-misaligned exception or an access-fault exception will be generated.

Check address alignment of AMO instructions

---

device.h
main.c
uart.c

The original keybord input handling in UART generates an extra endline character, which causes tab completion and vi editor fauilure.
This change incorparates termios function to address the above issue. Following this change, users can utilize the vi editor, benefit from tab completion, and exit semu by pressing Ctrl-a followed by x.

Handle UART input with termios

---

riscv.c

From spec, an instruction-address-misaligned exception is reported on the branch or jump instruction, implying rd would not be updated.
For simplicity, I keep `do_jump` function to handle branch instruction, and modify only `op_jump_link` function.
Reference: https://riscv.org/technical/specifications/ (section 2.2)

Handle misalignment properly in jump-link instruction

---

common.h
device.h
virtio-blk.c
virtio-net.c
virtio.h

Two adjustments are conducted in this pull request:
1. Replace the hard-coded register address checking with enum.
2. Handle the configuration space read / write with device-specific structures.

Refactor VirtIO MMIO register map handling

---

riscv.c

Refer to [RISC-V ISA spec](https://riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf) Chapter 6,  signed division overflow occurs only when the most-negative integer, $−2^{XLEN −1}$, is divided by $−1$. The quotient of signed division overflow is equal to the dividend, and the remainder is zero.

Fix signed division overflow case

---

riscv.c

The current implementation of the mul instruction does not guard against integer overflow, potentially leading to undefined behavior. Cast the operands to int64_t before performing the multiplication to ensure that the result can be accommodated without overflow. The lower 32 bits of the product are then extracted, preserving the correct uint32_t type.

Fix signed integer overflow in RV32M

---

main.c

The RV_MARCHID macro is defined using a left shift operation without explicitly specifying the type of the constant. This can lead to undefined behavior, specifically a shift too many bits issue.
Modify the RV_MARCHID definition to use the ULL suffix for the constant, ensuring it is treated as an unsigned long long. This eliminates the undefined behavior.

Fix undefined behavior in RV_MARCHID definition

---

minimal.dts

The DTC of version 1.6.1 generates the following warnings:
1. (unit_address_vs_reg) /soc: node has a reg or ranges property, but no unit name
2. (interrupt_provider): /cpus/cpu@0/interrupt-controller: Missing #address-cells in interrupt provider
To suppress them, add unit-name with parent-bus-address to the SOC node and #address-cells to the CPU interrupt controller.

Suppress DTC warnings

---

.ci/autorun.sh
.github/workflows/main.yml

This commit aims to automate the validation process by utilizing the 'expect' tool to verify if semu can successfully boot the Linux kernel and run BusyBox as anticipated. Currently, only the "uname" command is executed and its output is checked.

CI: Automate the runtime checks

---

minimal.dts

Per https://github.com/riscv-non-isa/riscv-device-tree-doc/blob/master/bindings/riscv/cpus.txt , the `mmu-type` attribute should be set to "riscv,sv32"

Fix incompatible mmu-type

---

Makefile
clint.c
device.h
main.c
minimal.dts
riscv.c
riscv.h
scripts/gen-hart-dts.py
utils.c
utils.h

Replace `mtime` counter by retrieving time of the specified clock ID. Also, Real time counter (RTC) mechanism is implemented to prevent `mtime` overflow.
Before:
```
[    0.000000] Linux version 6.1.94 (aaron@aaron-Lenovo-Y520-15IKBN) (riscv32-buildroot-linux-gnu-gcc.br_real (Buildroot 2024.02.3) 12.3.0, GNU ld (GNU Binutils) 2.41) #8 SMP Thu Jul 11 00:37:05 CST 2024
[    0.000000] Machine model: semu
[    0.000000] earlycon: ns16550 at MMIO 0xf4000000 (options '')
[    0.000000] printk: bootconsole [ns16550] enabled
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
...
[    2.687661] Freeing initrd memory: 8188K
[    2.691697] Freeing unused kernel image …
```

Replace mtime counter with realtime timer

---

utils.c

Introduces a new inline function, mult_frac(), to handle fractional multiplication with improved precision and safety by computing x * n / d while avoiding common issues like overflow and precision loss. Additionally, the semu_timer_clocksource() function has been refactored to use mult_frac() for time-related calculations, including the calculations for converting time derived from clock_gettime() and mach_absolute_time() into clock ticks. These updates collectively enhance the accuracy and reliability of time computations throughout the codebase.

Enhance precision and safety in time calculations

---

scripts/gen-hart-dts.py

Fix the device tree configuration by removing the interrupt-controller property from the clint node. The clint only handles timer and software interrupts, and should not be configured as an interrupt controller. Only the plic should be marked as an interrupt-controller as it manages external interrupts.
This change resolves the following dtc warnings about missing proper configuration of interrupt handling:
<stdin>:31.31-37.11: Warning (interrupt_provider): /soc@F0000000/clint@4300000: Missing #interrupt-cells in interrupt provider
<stdin>:31.31-37.11: Warning (interrupt_provider): /soc@F0000000/clint@4300000: Missing #address-cells in interrupt provider

Fix clint node in DTS by removing interrupt-controller property

---

feature.h

Rename macros with SEMU_FEATURE prefix
from SEMU_FEATUREXXX to SEMU_FEATURE_XXX.

Rename macros with SEMU_FEATURE prefix

---

common.h
virtio-blk.c
virtio-net.c

Introduce PACKED macro for cross-platform structure alignment, frequently used by VirtIO device implementations in the semu.

Introduce PACKED macro

---

utils.c

utils.c:49:9: error: use of undeclared identifier 'mach_clk'

Fix build on macOS

---

utils.c

The current `semu_timer_clocksource()` returns the clock source in nanoseconds when building on macOS. Causing an abnormal timestamp in the boot log.
```
...
[ 3062.927108] sched_clock: 64 bits at 65MHz, resolution 15ns, wraps every 2199023255550ns
```
Divide the return value by 1e9, ensuring the clock source is provided in seconds.

Fix incorrect clock calculation on macOS

---

utils.c

Improve the precision of semu_timer_clocksource() by deferring the division by 1e9 until the final step. Since t.numer and t.denom are typically much smaller compared to the clock frequency and 1e9, performing the division earlier in the calculation could result in a significant loss of precision. This change ensures that precision is preserved by delaying the division until the end of the computation.

Optimize semu_timer_clocksource() precision on macOS

---

scripts/build-image.sh

The GCC 14 now enforces a stricter error level by treating the `-Wimplicit-int` warning as an error by default. This change causes a compilation issue with the [libsha1](https://github.com/dottedmag/libsha1) library, which is necessary for enabling the X.Org Server.
Upgrading to Buildroot version [2024.11.1](https://github.com/buildroot/buildroot/releases/tag/2024.11.1) resolves this issue, as it includes a patch [1] that addresses the problem.
[1] [0001-test-fix-gcc-14.x-compile-implicit-int.patch](https://github.com/buildroot/buildroot/blob/65137580ca9ed060c59544b9859fc648e902c694/package/libsha1/0001-test-fix-gcc-14.x-compile-implicit-int.patch)

Bump Buildroot to the 2024.11.1 release

---

virtio-blk.c
virtio-net.c
virtio-rng.c
virtio.h

According to Virtio Specification Version 1.3, Section 2.7.5 *The Virtqueue Descriptor Table*, the type of `addr` should be `uint64_t` instead of `uint32_t`.
This commit addresses the error in the previous implementation.

Rectify length of Virtio descriptor address

---

.gitmodules
Makefile
device.h
main.c

Enable the emulator to act as gdbstub. This feature helps to dignose and debug issue of emulator more simply. 
<div id='description'>
<h3>Summary by Bito</h3>
This PR implements GDB remote debugging functionality by integrating mini-gdbstub library, adding debug mode with -g option, and restructuring the main emulation loop. The changes enable the emulator to function as a GDB remote target on port 1234, supporting interactive debugging through register/memory access and execution control features.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 4
</div>

Support GDB stub for remote debugging

---

Makefile
main.c
riscv.c
utils.c
utils.h

Since the emulator currently operates using sequential emulation, the execution time for the boot process is relatively long, which can result in the generation of RCU CPU stall warnings.
To address this issue, there are several potential solutions:
1. Scale the frequency to slow down emulator time during the boot process, thereby eliminating RCU CPU stall warnings.
2. During the boot process, avoid using 'clock_gettime' to update ticks and instead manage the tick increment relationship manually.
3. Implement multi-threaded emulation to accelerate the emulator's execution speed.
For the third point, while implementing multi-threaded emulation can significantly accelerate the emulator's execution speed, it cannot guarantee that this issue will not reappear as the number of cores increases …

Manage ticks to suppress RCU CPU stall warning

---

virtio-snd.c

Rectify accessing virtq struct members in virtio-sound device implementation. 
<div id='description'>
<h3>Summary by Bito</h3>
This PR enhances the virtio-sound device implementation by improving virtqueue descriptor member access methods. The changes focus on replacing direct array indexing with proper struct member access for better type safety and maintainability. The PR also includes function renaming for clarity and introduces proper memory alignment handling.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 1
</div>

Rectify accessing virtq struct members

---

main.c

Uninitialized hart_t fields may lead to undefined behavior or startup exceptions. This change replaces malloc with calloc to ensure that all fields are zeroed upon allocation, providing a safer and more consistent initialization.
Closed : #69  
<div id='description'>
<h3>Summary by Bito</h3>
This pull request enhances the safety of hart_t instance initialization by replacing malloc with calloc, ensuring all fields are zero-initialized upon allocation. This change addresses potential undefined behavior and improves consistency.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2 - The changes are straightforward and primarily focus on memory allocation safety, making the review process relatively simple.
</div>

Initialize harts with zero properly

---

main.c

To support register >64bits(e.g. AVX register on x86), the corresponding interface changes are made on mini-gdbstub. Synchronize the library and interface to the latest version to facilitate future development. This may also be helpful if we had Vector Extensions in the future.
Similar change made for rv32emu: https://github.com/sysprog21/rv32emu/pull/589

Update mini-gdbstub with the API changes

---

.ci/test-netdev.sh
.gitmodules
Makefile
device.h
main.c
netdev.c
netdev.h
slirp.c
virtio-net.c

This commit integrates 'minislirp' as submodule and enables support for the new 'user' network device, which uses SLIRP for user-mode networking.
An internal pipe mechanism is introduced to monitor incoming data. The main loop polls the pipe for availabe data, and any incoming data is forwarded to the virtio-net device for processing.
Additionally, this commit introduces special address used by SLIRP for network configuration [1]:
- **10.0.2.0**: The SLIRP "on-line" configuration address.
- **10.0.2.2**: An alias for the host running SLIRP.
- **10.0.2.3**: An alias for the DNS address.
- **10.0.2.15**: A recommended address for the PC running SLIRP.
1. Laumch `semu` with specified NETDEV=user
```
cd semu/
make check NETDEV=user
```
2. Configure the network interface with an IP address and …

Enable user-mode networking through SLIRP

---

Makefile

Fixes a compilation error introduced in #76, where the `make all` target fails during the build of the PortAudio library on GNU/Linux systems.
The failure was caused by PortAudio's configure script automatically enabling the sndio backend when `libsndio-dev` headers are present, which leads to linker errors due to missing `-lsndio`.
To avoid this, we now explicitly pass `--without-sndio` to PortAudio’s configure script. This ensures that sndio support is disabled regardless of system headers, eliminating the need for `-lsndio` and fixing the build.
* **Linux kernel:** 6.2.6-76060206-generic
* **Distribution:** Ubuntu 22.04.5 LTS (Jammy Jellyfish)
```
shengwen@pop-os:~/buildfarm/semu$ make all
LD	semu
/usr/bin/ld: portaudio/lib/.libs/libportaudio.a(pa_sndio.o): in function …
```

PortAudio: Disable sndio in PortAudio to avoid missing -lsndio errors

---

README.md
scripts/build-image.sh
scripts/rootfs_ext4.sh
target/init

Due to the 1 GiB kernel space limit on RV32-Linux, embedding large root filesystems in the kernel image can be impractical for certain testing scenarios.
This commit introduces a script to generate a mountable ext4 rootfs image and modifies the init script to support switching the root filesystem to a virtio-blk device.
During boot, the init script checks whether `/dev/vda` contains a valid rootfs. If so, it switches the root to the virtio-blk device. Otherwise, it falls back to the default initramfs.
**1. Build Linux kernel and rootfs CPIO**
```
$ cd semu/
$ ./scripts/build-image.sh --all
```
**2. Generate external rootfs image**
```
$ ./scripts/build-image.sh --all --external-root
```
**3. Launch the simulator**
```
$ make check
```
**Expected Output**
The console output should indicate …

Support mounting rootfs from virtio-blk via initrd

---

Makefile

Quote from portaudio/config.log:
...
configure:3194: checking whether the C compiler works
configure:3216: gcc  -I/opt/homebrew/opt/zlib/include portaudio/lib/.libs/libportaudio.a -framework CoreServices -framework CoreFoundation -framework AudioUnit -framewo    rk AudioToolbox -framework CoreAudio -lpthread -lm mini-gdbstub/build/libgdbstub.a conftest.c  >&5
clang: error: no such file or directory: 'portaudio/lib/.libs/libportaudio.a'
...
configure:3265: error: C compiler cannot create executables
...
The ./configure script fails on macOS because LDFLAGS includes static libraries (libportaudio.a) that have not yet been built. This causes the compiler check to fail with "C compiler cannot create executables".
This patch unsets LDFLAGS during the configure step to allow the test program to …

PortAudio: Enable build on macOS/arm64
